name: Build EXE

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Устанавливаем NuGet (для скачивания зависимостей)
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    # 2. Восстанавливаем библиотеки проекта
    - name: Restore dependencies
      run: nuget restore

    # 3. Устанавливаем классический MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 4. Собираем проект для Windows
    - name: Build
      run: msbuild /p:Configuration=Release

    # 5. Сохраняем результат
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MortarKiller-Build
        path: "**/bin/Release/**"
