name: Build EXE

on:
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x # или 7.0.x, зависит от проекта

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MortarKiller-Build
        path: "**/bin/Release/**"
